# Generated by Django 4.2.5 on 2023-09-10 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Описание', 'verbose_name_plural': 'Описания'},
        ),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
    ]
