# Generated by Django 4.2.5 on 2023-09-10 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_review_options_remove_book_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publish_date',
            field=models.IntegerField(max_length=4, verbose_name='Дата публикации'),
        ),
    ]
