# Generated by Django 4.2.5 on 2023-09-10 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_publish_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Описание', 'verbose_name_plural': 'Описание'},
        ),
        migrations.AddField(
            model_name='review',
            name='review_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата публикации'),
        ),
    ]
