# Generated by Django 4.2.5 on 2023-09-10 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_book_publish_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['rating'], 'verbose_name': 'Описание', 'verbose_name_plural': 'Описание'},
        ),
    ]
