# Generated by Django 4.2.5 on 2023-09-11 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_book_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='book',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='books.book', verbose_name='Книга'),
        ),
    ]
